name: JavaScript CI with npm

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use node 18.18.0
        uses: actions/setup-node@v2
        with:
          node-versions: 18.18.0
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test:unit


